stages:
  - test
  - report
  - deploy

variables:
  PYTHONUNBUFFERED: "1"
  WDM_LOG_LEVEL: "0"
  WDM_PROGRESS_BAR: "0"
  WDM_SSL_VERIFY: "0"

ui-tests:
  stage: test
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker info
    - mkdir -p allure-results screenshots
    - chmod -R 777 allure-results screenshots

  script:
    - docker build -t selenium-tests .
    - docker run --name selenium-test-container -v $(pwd)/allure-results:/app/allure-results -v $(pwd)/screenshots:/app/screenshots selenium-tests || true
  artifacts:
    paths:
      - allure-results/
      - screenshots/
    expire_in: 1 week
    when: always
  only:
    - main
  allow_failure: true

allure-report:
  stage: report
  image: frankescobar/allure-docker-service
  before_script:
    - ls -la allure-results || echo "Директория пуста или не существует"
  script:
    - allure generate allure-results -o allure-report --clean
  artifacts:
    paths:
      - allure-report/
    expire_in: 1 week
    when: always
  only:
    - main
  dependencies:
    - ui-tests
  needs:
    - ui-tests
  when: always

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r allure-report/* public
  artifacts:
    paths:
      - public
  only:
    - main
  dependencies:
    - allure-report
  when: always
